### PR TITLE
[ Feature request ] : Add new programs in string folder of jule

### PR DESCRIPTION
**Pull request by Jivanjamadar**
Added 2 files of jule programs :
StringReverse.jule - Main program for reversing the string 
StringReverseTest.jule - To test the program, there is test cases

### CODE REVIEW

**Comment by Jivanjamadar** [comment]
@mertcandav as you said, I have mentioned issue in PR. Please, review it. Thank you

**Review by mertcandav — CHANGES_REQUESTED** [review]
This implementation is invalid. First of all, it's not a valid Jule code. Have undefined semantics and invalid syntaxes. For example, `module reverse_string` is invalid. Jule have not such a semantics.

Also Jule variables are immutable-by-default but you are mutating the `s` parameter which is immutable. Also strings are not mutable, so you should cast into byte slice first. But reversing byte slice is not a correct approach. So you should cast string into rune slice, reverse rune slice, and return as string the rune slice.

There are too many issues. Such as `pub fn` or `return` keywords. Jule have `ret` keyword for return statements. Have no `pub` keyword and etc. Please write your code syntactically and semantically correct, and test it whether it compiles successfully.

**Comment by Jivanjamadar** [comment]
Sorry for inconvenience. I will make necessary changes. Thank you for suggesting changes.

**Comment by Jivanjamadar** [comment]
@mertcandav extremely sorry for deleting the head repository which causing to closing issue but I have done another PR for that please review that.

**Pull request closed without merging**
